name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory "$(pwd)"
      - uses: iffy/install-nim@v5
      - run: nimble test
      - run: nimble -d:release -d:danger test
